import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { Loading } from "@/components/ui/loading";

const roboto = Gabarito({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Fed Demat Holding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <Suspense fallback={<Loading description={"Loading"} />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
